WITH 
AVAILABLE_CARS AS (
  SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
  FROM CAR_RENTAL_COMPANY_CAR C
  WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01'
    )
),

DISCOUNT_30 AS (
  SELECT CAR_TYPE, DISCOUNT_RATE
  FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
  WHERE DURATION_TYPE LIKE '30%'
)

SELECT A.CAR_ID, A.CAR_TYPE,ROUND(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100) AS FEE
FROM AVAILABLE_CARS A JOIN  DISCOUNT_30 B ON A.CAR_TYPE = B.CAR_TYPE
WHERE ROUND(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC;





