SELECT E.ID,
     CASE
     WHEN E.PER <= 0.25 THEN 'LOW'
     WHEN E.PER BETWEEN 0.25 AND 0.5 THEN 'MEDIUM'
     WHEN E.PER BETWEEN 0.5 AND 0.75 THEN 'HIGH'
     ELSE 'CRITICAL'
     END AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY) AS PER
      FROM ECOLI_DATA) 
      AS E
ORDER BY E.ID;
  
    