WITH JOIN_21 AS (
    SELECT COUNT(*) AS SUM_USER 
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
    )

SELECT YEAR(SALES_DATE) AS YEAR,
       MONTH(SALES_DATE) AS MONTH,
       COUNT(DISTINCT(USER_ID)) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT(USER_ID)) / (SELECT SUM_USER FROM JOIN_21),1) AS PURCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID
                 FROM USER_INFO
                 WHERE YEAR(JOINED) = '2021')
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY 1,2;