WITH PICK_TRUCK AS (
    SELECT B.HISTORY_ID, A.DAILY_FEE, 
           DATEDIFF(B.END_DATE,B.START_DATE)+1 AS DURATION
    FROM CAR_RENTAL_COMPANY_CAR A 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
         ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE = '트럭'
), TRUCK_FEE AS (
    SELECT HISTORY_ID, DAILY_FEE, DURATION,
           CASE 
           WHEN DURATION >= 90 THEN '90일 이상'
           WHEN DURATION >= 30 THEN '30일 이상'
           WHEN DURATION >= 7  THEN '7일 이상'
           ELSE NULL
           END AS DURATION_TYPE
    FROM PICK_TRUCK 
) 

SELECT A.HISTORY_ID,
       CASE 
           WHEN A.DURATION_TYPE IS NULL
               THEN ROUND(A.DAILY_FEE * A.DURATION)
           ELSE ROUND(A.DAILY_FEE * A.DURATION * (1 - B.DISCOUNT_RATE * 0.01))
       END AS FEE
FROM TRUCK_FEE A LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B 
  ON B.CAR_TYPE = '트럭' AND A.DURATION_TYPE = B.DURATION_TYPE
ORDER BY FEE DESC, A.HISTORY_ID DESC;
