WITH NAME AS (SELECT A.MEMBER_ID, A.MEMBER_NAME
            FROM MEMBER_PROFILE A JOIN REST_REVIEW B ON A.MEMBER_ID=B.MEMBER_ID
            GROUP BY A.MEMBER_ID
            ORDER BY COUNT(*) DESC
            LIMIT 1)
            
SELECT B.MEMBER_NAME,A.REVIEW_TEXT, 
       DATE_FORMAT(A.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW A JOIN NAME B ON A.MEMBER_ID=B.MEMBER_ID
ORDER BY 3 ASC, 2 ASC ;